---
#  security:
#    basic:
#      enabled: false
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    health:
      show-details: always
      enabled: true
  info:
    git:
      mode: full

spring:
  application:
    name: probate-business-service
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      wrap_root_value: false
    deserialization:
      unwrap_root_value: true
  info:
    git:
      location: classpath:uk/gov/hmcts/probate/services/business/git.properties
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
services:
  auth:
    provider:
      totp_secret: "AAAAAAAAAAAAAAAA"
      baseUrl: http://localhost:4502
      microservice: "probate_backend"
      tokenTimeToLiveInSeconds: '900'
  persistence:
    baseUrl: http://localhost:8282
    invitedata:
      url: ${services.persistence.baseUrl}/invitedata
    formdata:
      url: ${services.persistence.baseUrl}/formdata
  notify:
    apiKey: "davejlive-fce47f9c-7bbe-4f41-829e-5144a3820768-191c9e6a-53c0-443b-8b30-cd7dd80e8764"
    invitedata:
      templateId: "3b8d806e-cc80-4729-b99a-19854ff60ad2"
      bilingualTemplateId: "23354df7-862c-4e8c-a500-50946df608c2"
      inviteLink: "http://localhost:3000/executors/invitation/"
    pin:
      templateId: "c0e11486-b8b3-4c22-a1ae-805a0ad2f641"
      bilingualTemplateId: "724a2e58-f0fd-421d-986d-ad5c4b5a47c2"
  pdf:
    service:
      url: http://localhost:5500
      pdfApi: /api/v2/pdf-generator/html
      templatesDirectory: templates/pdf/

document_management:
  url: http://localhost:5006
  fileupload:
    extensions: ".pdf .jpeg .jpg .bmp .tif .tiff .png"
    mimetypes: "image/jpeg application/pdf image/tiff image/png image/bmp"

idam:
  s2s-auth:
    url: ${services.auth.provider.baseUrl}

  logging:
    level:
      org.springframework.web: ERROR
      au.com.dius.pact: DEBUG
    pattern:
      console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"