apiVersion: v1
name: probate-business-service
home: https://github.com/hmcts/probate-business-service
version: 0.0.9
description: HMCTS Probate Business Service
maintainers:
  - name: HMCTS Probate Team
    email: Probate@hmcts.net
