java:
  applicationPort: 8080
  environment:
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: business-service
    SERVICES_NOTIFY_APIKEY: ${PRO_SERVICES_NOTIFY_APIKEY}
    SERVICES_NOTIFY_INVITEDATA_TEMPLATEID: ${PRO_SERVICES_NOTIFY_INVITEDATA_TEMPLATEID}
    SERVICES_NOTIFY_PIN_TEMPLATEID: ${PRO_SERVICES_NOTIFY_PIN_TEMPLATEID}
    SERVICES_AUTH_PROVIDER_TOTP_SECRET: ${S2S_AUTH_TOTP_SECRET}
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
