java:
  environment:
    SERVICES_PERSISTENCE_BASEURL : http://probate-persistence-service-aat.service.core-compute-aat.internal
    SERVICES_NOTIFY_INVITEDATA_INVITELINK : http://probate-frontend-aat.service.core-compute-aat.internal/executors/invitation/
    SERVICES_PDF_SERVICE_URL : http://cmc-pdf-service-aat.service.core-compute-aat.internal
    SERVICES_AUTH_PROVIDER_BASEURL : http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    DOCUMENT_MANAGEMENT_URL : http://dm-store-aat.service.core-compute-aat.internal
    SERVICES_NOTIFY_APIKEY: ${PRO_SERVICES_NOTIFY_APIKEY}
    SERVICES_NOTIFY_INVITEDATA_TEMPLATEID: ${PRO_SERVICES_NOTIFY_INVITEDATA_TEMPLATEID}
    SERVICES_NOTIFY_PIN_TEMPLATEID: ${PRO_SERVICES_NOTIFY_PIN_TEMPLATEID}
    SERVICES_AUTH_PROVIDER_TOTP_SECRET: ${S2S_AUTH_TOTP_SECRET}
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
